"""Context-tree mixture with layered leaves (scheme 1 of the outlook).

Prior over state maps generated by recursive tree growth: starting from
the empty context, each context splits into its per-token refinements with
probability 1/2, independently and recursively, up to maximal depth D.
This defines a prior over all variable-length suffix state maps (prunings
of the depth-D suffix tree).  For a FIXED pruning, the predictor is the
honest share-nothing construction: a per-leaf depth-averaged layered
mixture over the fixed emission vocabulary, evaluated exactly from the
leaf's successor count profile.  The mixture over ALL prunings is computed
without enumeration by the context-tree recursion

    beta(node) = 1/2 q_avg(node) + 1/2 prod_children beta(child)

for internal-capable nodes, and beta = q_avg at maximal depth, evaluated
bottom-up; the family codelength is -log2 beta(root).  All prunings code
tokens x_{D+1} .. x_n (earlier tokens lack a full context), so members are
mixable and comparable with fixed-depth baselines, which are reported too.

The MAP pruning (replace the sum by a max and keep back-pointers) is
reported as a diagnostic: how many leaves at which depths the data most
favors --- the effective-memory read-out of this family.

Computation reduces to one q_avg evaluation per distinct context observed
(depth <= D), with global deduplication of identical successor profiles.
"""

from __future__ import annotations

import math
from collections import Counter, defaultdict
from pathlib import Path
from typing import Sequence

from product_model_with_memory.codelength import (
    default_l_max,
    depth_averaged_codelength_profiles,
    profile_of,
)


def build_context_nodes(
    reduced: Sequence[str], max_depth: int
) -> dict[tuple[str, ...], Counter]:
    """Successor counts for every context of length 0..max_depth.

    The context of token x_t (t > max_depth, 0-indexed t >= max_depth) at
    depth d is (x_{t-1}, ..., x_{t-d}), most recent first.  Only tokens
    with a full max_depth history are counted, so every pruning's leaves
    partition the same coded tokens.
    """

    nodes: dict[tuple[str, ...], Counter] = defaultdict(Counter)
    n = len(reduced)
    for t in range(max_depth, n):
        token = reduced[t]
        for d in range(0, max_depth + 1):
            context = tuple(reduced[t - 1 - i] for i in range(d))
            nodes[context][token] += 1
    return dict(nodes)


def kt_log2_q(profile: tuple[int, ...], vocabulary_size: int) -> float:
    """log2 probability of a count profile under the KT (Dirichlet-1/2)
    estimator over a fixed alphabet of size V.

    P = Gamma(V/2) / Gamma(n + V/2) * prod_i Gamma(m_i + 1/2) / Gamma(1/2)
    over the nonzero counts m_i (zero counts contribute a factor 1).
    """

    V = vocabulary_size
    n = sum(profile)
    log = math.lgamma(V / 2.0) - math.lgamma(n + V / 2.0)
    half = math.lgamma(0.5)
    for m in profile:
        log += math.lgamma(m + 0.5) - half
    return log / math.log(2.0)


def context_tree_codelengths(
    reduced: Sequence[str],
    *,
    vocabulary_size: int,
    max_depth: int,
    l_max: int | None = None,
    cache_dir: str | Path,
    jobs: int = 1,
    leaf_model: str = "layered",
    progress=None,
) -> dict:
    """Context-tree-weighted codelength, plus baselines.

    leaf_model selects the per-node estimator: "layered" (depth-averaged
    layered mixture, the default) or "kt" (Krichevsky--Trofimov, i.e.
    Dirichlet-1/2, the classical CTW leaf; needs no moment tables).
    """

    if l_max is None:
        l_max = default_l_max(vocabulary_size)
    n_coded = len(reduced) - max_depth

    nodes = build_context_nodes(reduced, max_depth)
    profiles = {ctx: profile_of(counts) for ctx, counts in nodes.items()}
    unique = set(profiles.values())
    if progress is not None:
        progress(("profiles", len(unique), len(nodes)), None)

    if leaf_model == "kt":
        per_profile = {p: kt_log2_q(p, vocabulary_size) for p in unique}
        log2_q = {ctx: per_profile[p] for ctx, p in profiles.items()}
    elif leaf_model == "layered":
        results = depth_averaged_codelength_profiles(
            {p: p for p in unique},
            d=vocabulary_size,
            l_max=l_max,
            cache_dir=cache_dir,
            jobs=jobs,
            progress=progress,
        )
        log2_q = {ctx: results[p].log2_q_avg for ctx, p in profiles.items()}
    else:
        raise ValueError(f"unknown leaf_model: {leaf_model!r}")

    # children of each context (only observed ones carry data)
    children: dict[tuple[str, ...], list[tuple[str, ...]]] = defaultdict(list)
    for ctx in profiles:
        if len(ctx) > 0:
            children[ctx[:-1]].append(ctx)

    # bottom-up beta recursion (log2 domain) + MAP variant with choices
    log_beta: dict[tuple[str, ...], float] = {}
    log_gamma: dict[tuple[str, ...], float] = {}
    map_split: dict[tuple[str, ...], bool] = {}
    for depth in range(max_depth, -1, -1):
        for ctx in (c for c in profiles if len(c) == depth):
            if depth == max_depth:
                log_beta[ctx] = log2_q[ctx]
                log_gamma[ctx] = log2_q[ctx]
                map_split[ctx] = False
                continue
            child_beta = sum(log_beta[c] for c in children.get(ctx, []))
            child_gamma = sum(log_gamma[c] for c in children.get(ctx, []))
            leaf_term = -1.0 + log2_q[ctx]
            split_term = -1.0 + child_beta
            log_beta[ctx] = _log2addexp(leaf_term, split_term)
            if -1.0 + child_gamma > leaf_term:
                log_gamma[ctx] = -1.0 + child_gamma
                map_split[ctx] = True
            else:
                log_gamma[ctx] = leaf_term
                map_split[ctx] = False

    root = ()
    family_bits = -log_beta[root] / n_coded

    # fixed-depth baselines: complete tree at depth d
    fixed_depth_bits = {}
    for d in range(0, max_depth + 1):
        total = sum(log2_q[c] for c in profiles if len(c) == d)
        fixed_depth_bits[d] = -total / n_coded

    # MAP pruning diagnostic: walk the chosen tree, count leaves per depth
    map_leaves_by_depth: Counter = Counter()
    stack = [root]
    while stack:
        ctx = stack.pop()
        if map_split.get(ctx, False) and children.get(ctx):
            stack.extend(children[ctx])
        else:
            map_leaves_by_depth[len(ctx)] += 1
    map_bits = -log_gamma[root] / n_coded  # includes its prior cost

    return {
        "n_coded": n_coded,
        "l_max": l_max,
        "leaf_model": leaf_model,
        "max_depth": max_depth,
        "contexts_observed": len(nodes),
        "unique_profiles": len(unique),
        "family_bits_per_token": family_bits,
        "fixed_depth_bits_per_token": fixed_depth_bits,
        "map_bits_per_token": map_bits,
        "map_leaves_by_depth": dict(map_leaves_by_depth),
    }


def _log2addexp(a: float, b: float) -> float:
    m = max(a, b)
    return m + math.log2(2.0 ** (a - m) + 2.0 ** (b - m))
