"""Context-tree mixture with layered leaves (scheme 1 of the outlook).

Prior over state maps generated by recursive tree growth: starting from
the empty context, each context splits into its per-token refinements with
probability 1/2, independently and recursively, up to maximal depth D.
This defines a prior over all variable-length suffix state maps (prunings
of the depth-D suffix tree).  For a FIXED pruning, the predictor is the
honest share-nothing construction: a per-leaf depth-averaged layered
mixture over the fixed emission vocabulary, evaluated exactly from the
leaf's successor count profile.  The mixture over ALL prunings is computed
without enumeration by the context-tree recursion

    beta(node) = 1/2 q_avg(node) + 1/2 prod_children beta(child)

for internal-capable nodes, and beta = q_avg at maximal depth, evaluated
bottom-up; the family codelength is -log2 beta(root).  All prunings code
tokens x_{D+1} .. x_n (earlier tokens lack a full context), so members are
mixable and comparable with fixed-depth baselines, which are reported too.

The MAP pruning (replace the sum by a max and keep back-pointers) is
reported as a diagnostic: how many leaves at which depths the data most
favors --- the effective-memory read-out of this family.

Computation reduces to one q_avg evaluation per distinct context observed
(depth <= D), with global deduplication of identical successor profiles.
"""

from __future__ import annotations

import math
from collections import Counter, defaultdict
from pathlib import Path
from typing import Sequence

import numpy as np

from product_model_with_memory.counting import context_profile_tables

from product_model_with_memory.codelength import (
    default_l_max,
    depth_averaged_codelength_profiles,
    profile_of,
)


def build_context_nodes(
    reduced: Sequence[str], max_depth: int
) -> dict[tuple[str, ...], Counter]:
    """Successor counts for every context of length 0..max_depth.

    The context of token x_t (t > max_depth, 0-indexed t >= max_depth) at
    depth d is (x_{t-1}, ..., x_{t-d}), most recent first.  Only tokens
    with a full max_depth history are counted, so every pruning's leaves
    partition the same coded tokens.
    """

    nodes: dict[tuple[str, ...], Counter] = defaultdict(Counter)
    n = len(reduced)
    for t in range(max_depth, n):
        token = reduced[t]
        for d in range(0, max_depth + 1):
            context = tuple(reduced[t - 1 - i] for i in range(d))
            nodes[context][token] += 1
    return dict(nodes)


def kt_log2_q(profile: tuple[int, ...], vocabulary_size: int) -> float:
    """log2 probability of a count profile under the KT (Dirichlet-1/2)
    estimator over a fixed alphabet of size V.

    P = Gamma(V/2) / Gamma(n + V/2) * prod_i Gamma(m_i + 1/2) / Gamma(1/2)
    over the nonzero counts m_i (zero counts contribute a factor 1).
    """

    V = vocabulary_size
    n = sum(profile)
    log = math.lgamma(V / 2.0) - math.lgamma(n + V / 2.0)
    half = math.lgamma(0.5)
    for m in profile:
        log += math.lgamma(m + 0.5) - half
    return log / math.log(2.0)


def context_tree_codelengths(
    reduced: Sequence[str],
    *,
    vocabulary_size: int,
    max_depth: int,
    l_max: int | None = None,
    cache_dir: str | Path,
    jobs: int = 1,
    leaf_model: str = "layered",
    progress=None,
) -> dict:
    """Context-tree-weighted codelength, plus baselines.

    leaf_model selects the per-node estimator: "layered" (depth-averaged
    layered mixture, the default) or "kt" (Krichevsky--Trofimov, i.e.
    Dirichlet-1/2, the classical CTW leaf; needs no moment tables).
    """

    if l_max is None:
        l_max = default_l_max(vocabulary_size)
    n_coded = len(reduced) - max_depth

    # ---- counting by sorted packed keys (complexity notes, T4):
    # memory is a few flat arrays of size n, NOT proportional to the
    # number of distinct contexts (the old hash-table counting needed
    # ~200 GB at full vocabulary, depth 2)
    vocab_ids: dict[str, int] = {}
    ids = np.empty(len(reduced), dtype=np.int64)
    for i, tok in enumerate(reduced):
        idx = vocab_ids.get(tok)
        if idx is None:
            idx = len(vocab_ids)
            vocab_ids[tok] = idx
        ids[i] = idx
    if len(vocab_ids) > vocabulary_size:
        raise ValueError(
            f"{len(vocab_ids)} distinct tokens exceed vocabulary_size="
            f"{vocabulary_size}")
    tables = context_profile_tables(ids, vocabulary_size, max_depth)
    unique = tables.profiles
    contexts_observed = sum(tables.n_contexts)
    if progress is not None:
        progress(("profiles", len(unique), contexts_observed), None)

    if leaf_model == "kt":
        per_profile = [kt_log2_q(p, vocabulary_size) for p in unique]
    elif leaf_model == "layered":
        results = depth_averaged_codelength_profiles(
            {i: p for i, p in enumerate(unique)},
            d=vocabulary_size,
            l_max=l_max,
            cache_dir=cache_dir,
            jobs=jobs,
            progress=progress,
        )
        per_profile = [results[i].log2_q_avg for i in range(len(unique))]
    else:
        raise ValueError(f"unknown leaf_model: {leaf_model!r}")
    per_profile_arr = np.asarray(per_profile)
    q = [per_profile_arr[tables.profile_id[d]]
         for d in range(max_depth + 1)]  # log2 q_avg per context, per depth

    # ---- bottom-up beta recursion (log2 domain), vectorized per depth
    log_beta = [None] * (max_depth + 1)
    log_gamma = [None] * (max_depth + 1)
    map_split = [None] * (max_depth + 1)
    log_beta[max_depth] = q[max_depth].copy()
    log_gamma[max_depth] = q[max_depth].copy()
    map_split[max_depth] = np.zeros(tables.n_contexts[max_depth], dtype=bool)
    for d in range(max_depth - 1, -1, -1):
        child_beta = np.zeros(tables.n_contexts[d])
        child_gamma = np.zeros(tables.n_contexts[d])
        np.add.at(child_beta, tables.parent[d + 1], log_beta[d + 1])
        np.add.at(child_gamma, tables.parent[d + 1], log_gamma[d + 1])
        leaf_term = -1.0 + q[d]
        split_term = -1.0 + child_beta
        m = np.maximum(leaf_term, split_term)
        log_beta[d] = m + np.log2(
            np.exp2(leaf_term - m) + np.exp2(split_term - m))
        take_split = (-1.0 + child_gamma) > leaf_term
        log_gamma[d] = np.where(take_split, -1.0 + child_gamma, leaf_term)
        map_split[d] = take_split

    family_bits = -float(log_beta[0][0]) / n_coded

    # fixed-depth baselines: complete tree at depth d
    fixed_depth_bits = {
        d: -float(q[d].sum()) / n_coded for d in range(0, max_depth + 1)
    }

    # MAP pruning diagnostic: walk the chosen tree, count leaves per depth
    children_of: list[dict[int, list[int]] | None] = [None] * (max_depth + 1)
    for d in range(1, max_depth + 1):
        ch: dict[int, list[int]] = defaultdict(list)
        for child_idx, par in enumerate(tables.parent[d]):
            ch[int(par)].append(child_idx)
        children_of[d] = ch
    map_leaves_by_depth: Counter = Counter()
    stack = [(0, 0)]
    while stack:
        d, i = stack.pop()
        if (d < max_depth and map_split[d][i]
                and children_of[d + 1].get(i)):
            stack.extend((d + 1, c) for c in children_of[d + 1][i])
        else:
            map_leaves_by_depth[d] += 1
    map_bits = -float(log_gamma[0][0]) / n_coded  # includes its prior cost

    return {
        "n_coded": n_coded,
        "l_max": l_max,
        "leaf_model": leaf_model,
        "max_depth": max_depth,
        "contexts_observed": contexts_observed,
        "unique_profiles": len(unique),
        "family_bits_per_token": family_bits,
        "fixed_depth_bits_per_token": fixed_depth_bits,
        "map_bits_per_token": map_bits,
        "map_leaves_by_depth": dict(map_leaves_by_depth),
    }


def _log2addexp(a: float, b: float) -> float:
    m = max(a, b)
    return m + math.log2(2.0 ** (a - m) + 2.0 ** (b - m))
